-- V1：初始 schema —— 创建 widget 表。
--
-- 这份 DDL 是用 Hibernate 针对真正的 PostgreSQLDialect 导出后、人工整理字段顺序+注释得来的，
-- 所以它和 Widget 实体严格一致 —— 启动后 ddl-auto=validate 能校验通过。
--
-- 纪律：本文件一旦被 Flyway 执行过，就绝不再改一个字（Flyway 用 checksum 守这条线）。
-- 以后任何 schema 变更都新建 V2/V3... 往后追加。
create table widget (
    id         bigint        generated by default as identity primary key,
    name       varchar(64)   not null,
    sku        varchar(64)   not null unique,
    quantity   integer       not null,
    -- 枚举以字符串存储，Hibernate 自动加 CHECK 约束兜底（@Enumerated(STRING)）
    status     varchar(16)   not null check (status in ('ACTIVE', 'DISCONTINUED')),
    -- @Version 乐观锁版本号
    version    bigint,
    -- Instant → 带时区时间戳，这是真 Postgres 的类型，H2 只能近似
    created_at timestamp(6) with time zone not null
);
